remote_theme: pages-themes/minimal@v0.2.0
title: 9623M Robotics Notebook
logo: assets/img/warpdrive-color-lockup.svg
falcon: assets/img/warpdrive-color-symbol.svg
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
